### PR TITLE
Add a Helm chart for testing

### PR DESCRIPTION
**Pull request by dhaiducek**
Skeleton built from `helm create helm`, intended for testing the Helm capabilities in the policy generator

ref: https://issues.redhat.com/browse/ACM-9060

### CODE REVIEW

**Comment by dhaiducek** [comment]
Had to package it for Helm. Once merged, this chart should be accessible from:
```
https://github.com/stolostron/grc-e2e-policy-generator-test/raw/main/helm/
```

**Comment by mprahl** [comment]
@dhaiducek do you think you could add an optional variable that enables a `lookup` template function that should fail? That way, the test can test the happy path but also set a variable to expect a failure of the lookup. If the lookup doesn't fail, then the service account in App Sub has been granted privileges we were not expecting.

**Comment by dhaiducek** [comment]
@mprahl I've added an `enableLookup` variable that's disabled by default.

**Comment by dhaiducek** [comment]
...I also didn't add the env to the AppSub image, thinking it could be turned on manually--what do you think?

**Comment by mprahl** [comment]
> ...I also didn't add the env to the AppSub image, thinking it could be turned on manually--what do you think?

I don't think there's a way to add the custom environment variable without MCH overriding it. I think we should set the environment variable on by default in AppSub since as of now, it's safe and the test will catch the event that it becomes unsafe.

**Comment by dhaiducek** [comment]
> > ...I also didn't add the env to the AppSub image, thinking it could be turned on manually--what do you think?
> 
> I think we should set the environment variable on by default in AppSub since as of now, it's safe and the test will catch the event that it becomes unsafe.

Sounds good...so set it in the deployment so that it's somewhat configurable? ...or set it in the image itself?

**Comment by mprahl** [comment]
> > > ...I also didn't add the env to the AppSub image, thinking it could be turned on manually--what do you think?
> > 
> > 
> > I think we should set the environment variable on by default in AppSub since as of now, it's safe and the test will catch the event that it becomes unsafe.
> 
> Sounds good...so set it in the deployment so that it's somewhat configurable? ...or set it in the image itself?

Either way is fine. I think the image is fine for now and easier.

**Review by gparvin — APPROVED** [review]

**Pull request merged**
